# 5.0 Speech Feature Extraction

Purpose:
- Load speaker-safe speech split manifest
- Extract MFCC and basic acoustic features
- Save modeling-ready speech feature table

In [1]:
import pandas as pd
from tqdm import tqdm

from pathlib import Path
import sys

sys.path.insert(0, str(Path.cwd().parent))

tqdm.pandas()

from rural_stroke_assist.config import (
    SPEECH_SPLIT_MANIFEST_PATH,
    SPEECH_FEATURES_PATH,
    SPEECH_FEATURE_EXTRACTION_FAILURES_PATH
)
from rural_stroke_assist.features.speech_features import (
    build_speech_features_table,
)

In [2]:
speech_split_df = pd.read_csv(SPEECH_SPLIT_MANIFEST_PATH)

speech_split_df.head()

,path,file_name,extension,label,torgo_group,speaker_id,readable,duration_seconds,sample_rate,num_samples,split
0,C:\Users\Asus\Downloads\Uni_work\Grad-Project\...,wav_arrayMic_M01S01_0001.wav,.wav,dysarthric,M_Dys,wav_arrayMic_M01S01,True,9.30,16000.0,148800.0,train
1,C:\Users\Asus\Downloads\Uni_work\Grad-Project\...,wav_arrayMic_M01S01_0002.wav,.wav,dysarthric,M_Dys,wav_arrayMic_M01S01,True,7.80,16000.0,124800.0,train
2,C:\Users\Asus\Downloads\Uni_work\Grad-Project\...,wav_arrayMic_M01S01_0003.wav,.wav,dysarthric,M_Dys,wav_arrayMic_M01S01,True,8.10,16000.0,129600.0,train
3,C:\Users\Asus\Downloads\Uni_work\Grad-Project\...,wav_arrayMic_M01S01_0004.wav,.wav,dysarthric,M_Dys,wav_arrayMic_M01S01,True,6.15,16000.0,98400.0,train
4,C:\Users\Asus\Downloads\Uni_work\Grad-Project\...,wav_arrayMic_M01S01_0005.wav,.wav,dysarthric,M_Dys,wav_arrayMic_M01S01,True,12.30,16000.0,196800.0,train

In [3]:
speech_split_df.groupby(["split", "label"]).size()

split  label
test   control       1867
       dysarthric     982
train  control       6679
       dysarthric    4221
val    control       2909
       dysarthric     973
dtype: int64

In [4]:
speech_features_df, failed_features_df = build_speech_features_table(
    split_manifest=speech_split_df,
    target_sample_rate=16000,
    max_duration_seconds=5.0,
)

speech_features_df.head()

c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=686
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=150
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=955
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=156
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=939
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=155
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=667
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=422
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=421
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=417
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=1206
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=151
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=134
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=405
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=137
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=423
  warnings.warn(
c:\Users\Asus\Downloads\Uni_work\Grad-Project\autokeras_env\Lib\site-packages\librosa\core\spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=132
  warnings.warn(

,path,file_name,label,label_encoded,speaker_id,torgo_group,split,mfcc_1_mean,mfcc_2_mean,mfcc_3_mean,...,rms_mean,rms_std,zcr_mean,zcr_std,spectral_centroid_mean,spectral_centroid_std,spectral_bandwidth_mean,spectral_bandwidth_std,spectral_rolloff_mean,spectral_rolloff_std
0,C:\Users\Asus\Downloads\Uni_work\Grad-Project\...,wav_arrayMic_M01S01_0001.wav,dysarthric,1,wav_arrayMic_M01S01,M_Dys,train,-163.494843,56.581371,-30.107115,...,0.144104,0.102247,0.151883,0.121665,2042.334292,781.147275,1723.756351,442.497088,3784.583997,1448.862083
1,C:\Users\Asus\Downloads\Uni_work\Grad-Project\...,wav_arrayMic_M01S01_0002.wav,dysarthric,1,wav_arrayMic_M01S01,M_Dys,train,-196.675262,66.341858,-25.319544,...,0.108665,0.071716,0.154005,0.139137,1910.950448,865.713928,1632.424714,357.816673,3471.785430,1342.273322
2,C:\Users\Asus\Downloads\Uni_work\Grad-Project\...,wav_arrayMic_M01S01_0003.wav,dysarthric,1,wav_arrayMic_M01S01,M_Dys,train,-181.038422,52.951725,-29.189020,...,0.132562,0.098360,0.232347,0.199550,2342.658893,1164.214791,1703.955806,427.230919,3979.150080,1727.665199
3,C:\Users\Asus\Downloads\Uni_work\Grad-Project\...,wav_arrayMic_M01S01_0004.wav,dysarthric,1,wav_arrayMic_M01S01,M_Dys,train,-376.797882,17.045906,36.214321,...,0.007747,0.007332,0.417319,0.225873,3702.937939,1098.628999,2367.278508,269.317380,6438.893312,978.800780
4,C:\Users\Asus\Downloads\Uni_work\Grad-Project\...,wav_arrayMic_M01S01_0005.wav,dysarthric,1,wav_arrayMic_M01S01,M_Dys,train,-226.536652,40.652927,-18.713095,...,0.097521,0.098568,0.229228,0.181667,2410.353555,1014.842146,1835.126339,420.014444,4338.126990,1615.570376

In [5]:
speech_features_df.shape

(17630, 44)

In [6]:
speech_features_df.isna().sum().sort_values(ascending=False).head(20)

path                       0
file_name                  0
mfcc_5_std                 0
mfcc_6_std                 0
mfcc_7_std                 0
mfcc_8_std                 0
mfcc_9_std                 0
mfcc_10_std                0
mfcc_11_std                0
mfcc_12_std                0
mfcc_13_std                0
duration_seconds           0
rms_mean                   0
rms_std                    0
zcr_mean                   0
zcr_std                    0
spectral_centroid_mean     0
spectral_centroid_std      0
spectral_bandwidth_mean    0
spectral_bandwidth_std     0
dtype: int64

In [ ]:
SPEECH_FEATURES_PATH.parent.mkdir(parents=True, exist_ok=True)

speech_features_df.to_csv(SPEECH_FEATURES_PATH, index=False)
failed_features_df.to_csv(SPEECH_FEATURE_EXTRACTION_FAILURES_PATH, index=False)

print("Saved features to:", SPEECH_FEATURES_PATH)
print("Saved failures to:", SPEECH_FEATURE_EXTRACTION_FAILURES_PATH)

Saved features to: C:\Users\Asus\Downloads\Uni_work\Grad-Project\rural-stroke-assist\data\processed\speech_features.csv
Saved failures to: C:\Users\Asus\Downloads\Uni_work\Grad-Project\rural-stroke-assist\data\processed\speech_feature_extraction_failures.csv

: